mesh_name: OneSidedWallBox
subfolder: OneSidedWallBox
save_fold: PreliminaryResults
geom_folder: ./Geometries/
surf_markers_anchoring: [1]
surf_markers_moving: [1]
maxIter: 100
dimensions: 3
rel_change_stopping_value: 1e-2
finite_element: "CG"
finite_element_degree: 1
initial_guess: "Frank"
forward_solver_relaxations: [[0.8, 1.e-4],[1.0, 1.e-8]] # !!! the . before the e in the scientific notation is needed for yaml parsing in arrays
target_geometry: "uniform_horizontal"
inner_product: "elasticity"
anchoring: "vertical"
tangential_smoothing: False
use_normal_dJds_projection: True
boundary_conditions_shapegradient: "None"
boundary_conditions_shapegradient_markers: [2]
sigma: 1e-5
beta: 0.5
stepsize_method: "constant"
herzog_meshquality_min: 1.e-1
alphaInit: 1.e2
alphaMin: 1.e-5
k_bc: 1.e10
E: 10
nu: 0.4
a_B: 0.1
L_c: 2e-1
delta: 1
delta_beltrami: 0