mesh_name: RoundedRectangle5to1EvenFinerMesh
subfolder: RoundedRectangle5to1EvenFinerMesh
save_fold: Results
geom_folder: ./Geometries/
surf_markers: [9]
maxIter: 1000
rel_change_stopping_value: 1e-2
finite_element: "CG"
finite_element_degree: 1
target_geometry: "defect"
top_charge: [0.5, 0.5]
position_defect: [[-0.5,0],[0.5,0]]
inner_product: "elasticity"
anchoring: "vertical"
tangential_smoothing: True
use_normal_dJds_projection: True  
sigma: 1e-1
beta: 0.5
alphaInit: 2e3
alphaMin: 1e-8
k_vol: 0.0
k_com: 1e18
k_bc: 1e4
k_boundary: 0
k_meshquality: 0
eps_meshquality: 1e-12
k_boundarylength: 0
k_edge: 0
E: 1
nu: 0.4
a_B: 0.1
L_c: 2e-6
beta_param: 5.0
x0: 1.5
delta: 0.8
delta_beltrami: 0.1