mesh_name: Ellipse2
subfolder: Ellipse2
save_fold: Results
geom_folder: ./Geometries/
surf_markers: [10]
maxIter: 1000
dimensions: 2
rel_change_stopping_value: 1e-2
finite_element: "CG"
finite_element_degree: 1
target_geometry: "circle"
top_charge: [0.5, 0.5]
position_defect: [[-0.5,0],[0.5,0]]
inner_product: "elasticity"
anchoring: "vertical"
tangential_smoothing: True
use_normal_dJds_projection: True
boundary_conditions_shapegradient: "None"
sigma: 1e-2
beta: 0.5
stepsize_method: "constant"
alphaInit: 1e3
alphaMin: 1e-8
k_vol: 0.0
k_com: 0.0
k_boundary: 0
k_meshquality: 0
k_bc: 1e4
eps_meshquality: 1e-12
k_boundarylength: 0
k_edge: 0
E: 1
nu: 0.4
a_B: 0.1
L_c: 2e-6
beta_param: 5.0
x0: 1.5
delta: 0.5
delta_beltrami: 0.5
