mesh_name: Rectangle2Sides2
subfolder: Rectangle2Sides2
save_fold: PreliminaryResults
geom_folder: ./Geometries/
surf_markers_anchoring: [1]
surf_markers_moving: [1]
maxIter: 100
dimensions: 2
rel_change_stopping_value: 1e-3
abs_change_stopping_value: 1e-8
finite_element: "CG"
finite_element_degree: 1
initial_guess: "uniform"
forward_solver_relaxations: [[1.0, 1.e-8]] # !!! the . before the e in the scientific notation is needed for yaml parsing
target_geometry: "uniform_vertical"
inner_product: "elasticity"
anchoring: "vertical"
tangential_smoothing: True
use_normal_dJds_projection: True
boundary_conditions_shapegradient: "None"
boundary_conditions_shapegradient_markers: [2]
sigma: 1e-6
beta: 0.5
stepsize_method: "constant"
herzog_meshquality_min: 1.e-1
alphaInit: 1e4
alphaMin: 1e-5
k_bc: 1e4
E: 1
nu: 0.4
a_B: 0.1
L_c: 2e-6
delta: 0.01
delta_beltrami: 0.1