mesh_name: RoundedRectangle
subfolder: RoundedRectangle
save_fold: PreliminaryResults
geom_folder: ./Geometries/
surf_markers_anchoring: [9]
surf_markers_moving: [9]
maxIter: 100
dimensions: 2
rel_change_stopping_value: 1e-2
finite_element: "CG"
finite_element_degree: 1
initial_guess: "Frank"
forward_solver_relaxations: [[1.0, 1.e-8]] # !!! the . before the e in the scientific notation is needed for yaml parsing
target_geometry: "circle"
top_charge: [0.5, 0.5]
position_defect: [[-0.5,0],[0.5,0]]
inner_product: "elasticity"
anchoring: "vertical"
tangential_smoothing: True
use_normal_dJds_projection: True
boundary_conditions_shapegradient: "None"
boundary_conditions_shapegradient_markers: [2]
sigma: 1e-5
beta: 0.5
stepsize_method: "constant"
alphaInit: 1e3
alphaMin: 1e-8
k_bc: 1e4
E: 1
nu: 0.4
a_B: 0.1
L_c: 2e-6
delta: 1
delta_beltrami: 0.5
